spring.application.name=Venta_de_Boletos

# Configuración para PostgreSQL en Render
spring.datasource.url=jdbc:postgresql://dpg-d6t6jgruibrs73cniq20-a.oregon-postgres.render.com:5432/datosv?sslmode=require
spring.datasource.username=datosv_user
spring.datasource.password=8hoJ08rjKEzzH0syp2HtuWEwhyLIXKyD
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pool de conexiones Hikari
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000